plugin: yacloud_compute
yacloud_token: AQAAAAAT_DPvAATuwTbSY1ehzUEOvhVv1M17Sok
yacloud_clouds:
 - cloud-lyulinve
yacloud_folders:
 - infra
strict: False
# группы не работают в plugin yacloud_compute
# см. ansible/playbooks/inventory_plugins/yacloud_compute.py 
# def _process_hosts(self):
# self.inventory.add_host(instance["name"], group="yacloud")
groups:
 docker: inventory_hostname.startswith('docker')
